---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Arista DNS Servers
  hosts: arista
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_command_timeout: 300
  tasks:
    # sh ip name-server
    - name: Create DNS Servers (Arista) 
      arista.eos.eos_config:
        lines:
          - "ip name-server {{ item }}"
      loop: "{{ dns_servers }}"
      become: true
      register: _dns_servers

    - name: Arista EOS Debug DNS Servers before
      debug:
        var: _dns_servers.before

    - name: Arista EOS Debug DNS Servers command
      debug:
        var: _dns_servers.commands

    - name: Arista EOS Debug DNS Servers after
      debug:
        var: _dns_servers.after

    - name: Save Arista EOS running to startup when modified
      arista.eos.eos_config:
        save_when: modified
      become: true

- name: Config Cisco DNS Servers
  hosts: cisco
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_command_timeout: 300
  tasks:
    - name: Create DNS Servers (Cisco) 
      cisco.ios.ios_config:
        lines:
          - "ip name-server {{ item }}"
      loop: "{{ dns_servers }}"
      become: true
      register: _dns_servers

    - name: Cisco IOS Debug DNS Servers before
      debug:
        var: _dns_servers.before

    - name: Cisco IOS Debug DNS Servers command
      debug:
        var: _dns_servers.commands

    - name: Cisco IOS Debug DNS Servers after
      debug:
        var: _dns_servers.after

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
      become: true

- name: Config Juniper DNS Servers
  hosts: juniper
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    - name: Create DNS Servers (Juniper) 
      junipernetworks.junos.junos_config:
        lines:
          - "set system name-server {{ item }}"
      loop: "{{ dns_servers }}"
      become: true
      register: _dns_servers

    - name: Juniper OS Debug DNS Servers before
      debug:
        var: _dns_servers.before

    - name: Juniper OS Debug DNS Servers command
      debug:
        var: _dns_servers.commands

    - name: Juniper OS Debug DNS Servers after
      debug:
        var: _dns_servers.after

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true

    # - name: Rollback Juniper OS configuration to id 10
    #   junipernetworks.junos.junos_config:
    #     rollback: 10

    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true


- name: Config Cisco XR DNS Servers
  hosts: ciscoxr
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_user: root
    ansible_connection: network_cli
    ansible_network_os: iosxr
    ansible_command_timeout: 300
  tasks:
    # sh running-config name-server
    - name: Create DNS Servers (Cisco XR) 
      cisco.iosxr.iosxr_config:
        lines:
          - "ip name-server {{ item }}"
      loop: "{{ dns_servers }}"
      become: true
      register: _dns_servers
      
    - name: Cisco XR Debug DNS Servers before
      debug:
        var: _dns_servers.before

    - name: Cisco XR Debug DNS Servers command
      debug:
        var: _dns_servers.commands

    - name: Cisco XR Debug DNS Servers after
      debug:
        var: _dns_servers.after

