---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Arista Banner
  hosts: arista
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_command_timeout: 300
  tasks:
    # sh banner login
    - name: Create Banner (Arista)
      arista.eos.eos_banner:
        banner: login
        text: "{{ banner.login }}"
        state: present
      become: true
      register: _banner

    - name: Arista EOS Debug Banner command
      debug:
        var: _banner.commands

    - name: Save Arista EOS running to startup when modified
      arista.eos.eos_config:
        save_when: modified
      become: true

- name: Config Cisco Banner
  hosts: cisco
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_command_timeout: 300
  tasks:
    # sh banner login
    - name: Create Banner (Cisco)
      cisco.ios.ios_banner:
        banner: login
        text: "{{ banner.login }}"
        state: present
      become: true
      register: _banner

    - name: Cisco IOS Debug Banner before
      debug:
        var: _banner.before

    - name: Cisco IOS Debug Banner command
      debug:
        var: _banner.commands

    - name: Cisco IOS Debug Banner after
      debug:
        var: _banner.after

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
      become: true

- name: Config Juniper Banner
  hosts: juniper
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    # sh banner login
    - name: Create Banner (Juniper)
      junipernetworks.junos.junos_banner:
        banner: login
        text: "{{ banner.login }}"
        state: present
      become: true
      register: _banner

    - name: Juniper OS Debug Banner before
      debug:
        var: _banner.before

    - name: Juniper OS Debug Banner command
      debug:
        var: _banner.commands

    - name: Juniper OS Debug Banner after
      debug:
        var: _banner.after

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true

    # - name: Rollback Juniper OS configuration to id 10
    #   junipernetworks.junos.junos_config:
    #     rollback: 10

    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true


- name: Config Cisco XR Banner
  hosts: ciscoxr
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_user: root
    ansible_connection: network_cli
    ansible_network_os: iosxr
    ansible_command_timeout: 300
  tasks:
    # sh banner login
    - name: Create Banner (Cisco XR)
      cisco.iosxr.iosxr_banner:
        banner: login
        text: "{{ banner.login }}"
        state: present
      become: true
      register: _banner

    - name: Cisco XR Debug Banner before
      debug:
        var: _banner.before

    - name: Cisco XR Debug Banner command
      debug:
        var: _banner.commands

    - name: Cisco XR Debug Banner after
      debug:
        var: _banner.after