---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Cisco EVPN
  hosts: cisco
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_command_timeout: 300
  tasks:
    - name: Create EVPN Config (Cisco) 
      cisco.ios.ios_config:
        lines:
          - "ip name-server 8.8.8.8"
      become: true

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
      become: true

- name: Config Juniper EVPN
  hosts: juniper
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    - name: Create EVPN (Juniper) 
      junipernetworks.junos.junos_config:
        src: junos_evpn.j2
        # lines:
        #   - "set system name-server 8.8.8.8"
      become: true
      vars: 
        ip_address: 8.8.8.8

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true

    # - name: Rollback Juniper OS configuration to id 10
    #   junipernetworks.junos.junos_config:
    #     rollback: 10

    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true


- name: Config Cisco XR EVPN
  hosts: ciscoxr
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: iosxr
    ansible_command_timeout: 300
  tasks:
    - name: Create EVPN Config (Cisco) 
      cisco.iosxr.iosxr_config:
        src: iosxr_evpn.j2
        # lines:
        #   - "ip name-server 8.8.8.8"
      become: true
      vars: 
        ip_address: 8.8.8.8


    # - name: Save running to startup when modified
    #   cisco.iosxr.iosxr_config:
    #     save_when: modified
    #   become: true
