---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Show Command parsing (Survey)
  hosts: cisco
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_command_timeout: 300
  tasks:
    - name: Run '{{ command }}' and parse with '{{ parser }}'
      ansible.utils.cli_parse:
        command: "{{ command }}"
        parser:
          name: "{{ parser }}"
      when: template is not defined
      register: _int_result

    - name: Debug '{{ command }}' and parse with '{{ parser }}'
      debug:
        var: _int_result.parsed
      when: template is not defined

    - name: Run '{{ command }}' and parse with '{{ parser }}' with '{{ template }}
      ansible.utils.cli_parse:
        command: "{{ command }}"
        parser:
          name: "{{ parser }}"
          template_path: "templates/{{ template }}"
      when: template is defined
      register: _int_result

    - name: Debug '{{ command }}' and parse with '{{ parser }}' with '{{ template }}
      debug:
        var: _int_result.parsed
      when: template is defined
