---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Arista VLANs
  hosts: arista
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_command_timeout: 300
  tasks:
    # sh vlan
    - name: Arista EOS Config VLAN
      arista.eos.eos_vlans:
        config: "{{ vlans }}"
        state: overridden
      register: _vlan
      become: yes

    - name: Arista EOS Debug VLANs before
      debug:
        var: _vlan.before

    - name: Arista EOS Debug VLANs command
      debug:
        var: _vlan.commands

    - name: Arista EOS Debug VLAN after
      debug:
        var: _vlan.after

    # sh interfaces status
    - name: Arista EOS Add VLAN to l2 interfaces
      arista.eos.eos_l2_interfaces:
        config: "{{ l2_interfaces_arista }}"
        state: overridden
      register: _l2_interface_arista
      become: true

    - name: Arista EOS Debug VLAN before
      debug:
        var: _l2_interface_arista.before

    - name: Arista EOS Debug VLAN command
      debug:
        var: _l2_interface_arista.commands

    - name: Arista EOS Debug VLAN after
      debug:
        var: _l2_interface_arista.after

    - name: Save Arista EOS running to startup when modified
      arista.eos.eos_config:
        save_when: modified
      become: true


- name: Config Juniper VLANs
  hosts: juniper
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    # sh vlan
    - name: Juniper OS Config VLAN
      junipernetworks.junos.junos_vlans:
        config: "{{ vlans }}"
        state: overridden
      register: _vlan
      become: yes

    - name: Juniper OS Debug VLANs before
      debug:
        var: _vlan.before

    - name: Juniper OS Debug VLANs command
      debug:
        var: _vlan.commands

    - name: Juniper OS Debug VLANs before
      debug:
        var: _vlan.after

    # # sh groups aws-default interfaces
    # - name: Juniper OS Add VLAN to l2 interfaces
    #   junipernetworks.junos.junos_l2_interfaces:
    #     config: "{{ l2_interfaces_juniper }}"
    #     state: overridden
    #   register: _l2_interface_juniper
    #   become: true

    # - name: Juniper OS Debug VLAN before
    #   debug:
    #     var: _l2_interface_juniper.before

    # - name: Juniper OS Debug VLAN command
    #   debug:
    #     var: _l2_interface_juniper.commands

    # - name: Juniper OS Debug VLAN before
    #   debug:
    #     var: _l2_interface_juniper.after

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true

    # - name: Rollback Juniper OS to last commit
    #   junipernetworks.junos.junos_config:
    #     rollback: 0

    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true
